# Generated by Django 4.2.18 on 2025-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('route_name', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=2000)),
                ('status_code', models.IntegerField()),
                ('duration_ms', models.FloatField()),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField()),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
