# Generated by Django 4.2.18 on 2025-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
